service: blank-python

frameworkVersion: '3'

provider:
  name: aws
  region: ${env:REGION}
  runtime: python3.8
  iam:
    role:
      name: blank-python-role
      managedPolicies:
        - arn:aws:iam::${env:AWS_ACCOUNT_NO}/AWSLambdaBasicExecutionRole
        - arn:aws:iam::${env:AWS_ACCOUNT_NO}/AWSLambda_ReadOnlyAccess
        - arn:aws:iam::${env:AWS_ACCOUNT_NO}/AWSXrayWriteOnlyAccess

functions:
  blank-python:
    handler: function.lambda_function.lambda_handler
    timeout: 300
    memorySize: 2048
    description: 'Call the AWS Lambda API'

plugins:
  - serverless-python-requirements
  - serverless-layers

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 3
  serverless-layers:
    functions:
      - blank-python
    dependenciesPath: package/.
    description: 'Dependencies for the blank-python sample app'
